Private/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',views.admin_private),
    path('view/',views.admin_private_view),
    path('view/<int:hid>',views.private_view),
    path('logout/',views.logout_private_admin),
    path('updatepra/',views.updatepra),
    path('remove_pri/<int:hid>',views.remove_pri),
    path('remove_photo/<int:hid>',views.remove_photo),
    path('download_data/', views.download_data),
]

User/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .views import *

urlpatterns = [
    # path('change-password/' , change_password , name='change_passwordd'),
    # path('accounts/login/' , login_attempt , name="login_attempt"),
    # path('logout/', logout , name = 'logout'),

    path('register/', register_attempt, name="register_attempt"),
    path('token', token_send, name="token_send"),
    path('verify/<auth_token>', verify, name="verify"),

    # path('password-reset/' , forget_passward , name="password_resett"),

    # path('password-reset/done/',
    #     auth_views.PasswordResetDoneView.as_view(
    #         template_name='user/password_reset_done.html'
    #     ),
    #     name='password_reset_done'
    # ),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='user/password_reset_confirm.html',
             success_url='/user/password-reset-complete/'
         ),
         name='password_reset_confirmm'
         ),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='user/password_reset_complete.html'
         ),
         name='password_reset_complete'
         ),

]

# handler404 = 'User.views.error_404'

private_info/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib import admin
from django.views.static import serve
from django.contrib.auth.decorators import login_required
from Private.models import PrivateModel, Private_SubModel
from django.shortcuts import redirect
from Private.views import some_view
from django.contrib import messages
from django.contrib.auth.models import User


# from django.conf.urls import url as url_e


# def custom_login_required(view_func):
#     def wrapper(request, *args, **kwargs):
#         check = some_view(request)
#         if int(check) == 1:
#             return redirect('/logout/')
#         else:
#             if request.session.get('private_admin'):
#                 # user2 = request.session.get('private_admin')
#                 # user_obj2 = User.objects.get( username = user2)
#                 # 
#                 s = view_func(request, *args, **kwargs)
#                 messages.success(request,   check)
#                 return redirect('/view/61')
#                 # print(view_func(request, *args, **kwargs))
#                 return view_func(request, *args, **kwargs)
#             else:
#                 return redirect('/')
        
#     return wrapper


def custom_login_required(view_func):
    def wrapper(request, *args, **kwargs):
        check = some_view(request)
        if int(check) == 1:
            return redirect('/logout/')
        else:
            if request.session.get('private_admin'):
                user2 = request.session.get('private_admin')
                link = request.path.split('uploads/')[1]
                check = Private_SubModel.objects.get(private_img=link)
                # messages.success(request,   f'{check.private_id.user.username} {user2}')
                if str(check.private_id.user.username).lower() == str(user2).lower():
                    return view_func(request, *args, **kwargs)
                else:
                    return redirect('/view/')
            else:
                return redirect('/')
        
    return wrapper


@custom_login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


urlpatterns = [
    path('admin_side/', admin.site.urls),
    path('',include('Private.urls')),
    path('user/',include('User.urls')),
    re_path(r'^uploads/(?P<path>.*)$', protected_serve,{'document_root':settings.MEDIA_ROOT}),
]

handler404 = "Private.views.page_not_found_view"

Private/models.py
from django.db import models
import os
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth.models import User


class PrivateModel(models.Model):
    date_name = models.DateField()
    private_description = models.TextField(null = True)
    user = models.ForeignKey(User ,on_delete=models.CASCADE, null = True)

    def __str__(self):
        return "%s" % (self.date_name)


class Private_SubModel(models.Model):
    private_id = models.ForeignKey(PrivateModel, on_delete = models.CASCADE,null=True)
    private_img = models.FileField(null =True ,upload_to = 'Private/PrivateImage')
    type = models.CharField(max_length = 50)
    def delete(self, *args, **kwargs):
        # Delete the image file when the product is deleted
        os.remove(self.private_img.path)
        super(Private_SubModel, self).delete(*args, **kwargs)

    def __str__(self):
        return "%s" % (self.private_id)

@receiver(pre_delete, sender=PrivateModel)
def delete_subcategory_images(sender, instance, **kwargs):
    subcategories = Private_SubModel.objects.filter(private_id=instance)

    # Delete subcategory images
    for subcategory in subcategories:
        image_path = os.path.join(settings.MEDIA_ROOT, str(subcategory.private_img))
        if os.path.exists(image_path):
            os.remove(image_path)

Private/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import PrivateModel


class PrivateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['private_description'].required = False
        self.fields['date_name'].widget = forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
            }
        )

    class Meta:
        model = PrivateModel
        exclude = ['user']
        fields = ['date_name', 'private_description']

Private/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from django.contrib.auth.backends import UserModel
from Private.models import PrivateModel, Private_SubModel
from Private.forms import PrivateForm
from Private.serializer import PrivateSerialize
from rest_framework.response import Response
from rest_framework.decorators import api_view
from datetime import datetime, timedelta
from django.http import JsonResponse
from googleapiclient.http import MediaFileUpload
from Private.Google import Create_Service
import os


# 404 Page Not Found
def page_not_found_view(request, exception):
    return render(request, '404.html', status=404)


# Private LogIn Screen
def admin_private(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        userobj = User.objects.filter(username = username).first()
        user_obj = User.objects.filter(email = username).first()
        if userobj:
            pass
        if user_obj:
            userobj = user_obj
        if (userobj) is None:
            messages.success(request, 'Username/Email not found.')
            return redirect(request.META.get('HTTP_REFERER'))

        if not (userobj).is_superuser:
            messages.success(request, "User Can't login")
            return redirect(request.META.get('HTTP_REFERER'))

        if (userobj).is_superuser:
            if userobj.is_staff:
                try:
                    user = UserModel.objects.get(email=username)
                    user11 = authenticate( username = user , password = password)
                    if (user11) is None:
                        messages.success(request, 'Wrong Password.')
                        return redirect('/')

                    # login(request , user11)
                    request.session['private_admin'] = user11.username
                    request.session['private_id'] = user11.id
                    request.session['login_time'] = datetime.now().timestamp()
                    return redirect('/view/')

                except:
                    usee = None;

                user1 = authenticate( username = username , password = password)

                if (user1 or usee ) is None:
                    messages.success(request, 'Wrong Password.')
                    return redirect('/')

                # login(request , user1)
                request.session['private_admin'] = user1.username
                request.session['private_id'] = user1.id
                request.session['login_time'] = datetime.now().timestamp()
                return redirect('/view/')


    # elif request.method == 'GET':
    return render(request , 'login.html',{"checkcon":0, "Title":"Private "})

    # elif 'username' in request.session:
    #     return redirect('/user/dashboard/')


# Private LogOut
def logout_private_admin(request):
    if 'private_admin' in request.session:
        del request.session['private_admin']
        del request.session['login_time']
        try:
            del request.session['private_id']
        except:
            pass
    # logout(request)
    return redirect('/')


# Logout Every 30 minutes
def some_view(request):
    return 0
    # Check if session has expired
    login_time = request.session.get('login_time')
    if login_time:
        login_time = datetime.fromtimestamp(login_time)
        if datetime.now() - login_time > timedelta(minutes=30):
            check = 1
        else:
            check = 0
    else:
        check = 1
    check = 0
    return check


# View All Details
def admin_private_view(request):
    check = some_view(request)
    if int(check) == 1:
        return redirect('/logout/')
    else:
        if request.method == 'POST':
            try:
                id = request.POST.get('id')
                jj = PrivateModel.objects.get(id=id)
                d = PrivateForm(request.POST or None,instance=jj,)
            except:
                d = PrivateForm(request.POST)
            if d.is_valid():
                user_id = request.session.get('private_id')
                user_obj = User.objects.get(id = user_id)
                private_data = d.save(commit=False)
                private_data.user = user_obj
                private_data.save()
                id = private_data.id
                return redirect(f'/view/{id}')
            else:
                return redirect(f'/view/')
        else:
            if 'private_admin' in request.session:
                d = PrivateForm()
                user2 = request.session.get('private_admin')
                user_obj2 = User.objects.get( username = user2)
                b = PrivateModel.objects.filter(user=user_obj2).order_by('-date_name')
                # b = PrivateModel.objects.all()
                x = {'m':d,'list':b,'private_master':'master','private_active':'private_master', "private_1":0, "checkcon":0}
            else:
                return redirect('/')
        return render(request , 'private_des.html', x)
        

# View All Photo, Add Photo 
def private_view(request,hid):
    check = some_view(request)
    if int(check) == 1:
        # call this fun logout_private_admin()
        return redirect('/logout/')
    else:
        if request.method == 'POST':
            id = request.POST.get("p_id")
            myfile = request.FILES.getlist("private_img")

            for f in myfile:
                chek = str(f).split('.')[-1]
                if (chek == "mp4"):
                    type = "video"
                else:
                    type = "photo"
                pro_obj = Private_SubModel()
                pri_id = PrivateModel.objects.get(id = id)
                pro_obj.private_id = pri_id
                pro_obj.private_img = f
                pro_obj.type = type
                pro_obj.save()

            return redirect(f"/view/{hid}")
        else:
            if 'private_admin' in request.session:
                user2 = request.session.get('private_admin')
                order = PrivateModel.objects.get(id=hid)
                if order.user.username == user2:
                    pro_list = Private_SubModel.objects.filter(private_id=hid)
                    d = PrivateForm()
                    data = {'m':d,'private_master':'master','private_activee':'private_masterr','lists':pro_list,'order':order,"private_1":0, "checkcon":0}
                else:
                    return redirect('/view/')
            else:
                return redirect('/')
            return render(request , 'private.html', data)


# Private Detail Function
@api_view(['POST'])
def updatepra(request):
    id = request.POST.get('id')
    get_data = PrivateModel.objects.get(id = id)
    serializer = PrivateSerialize(get_data)
    return Response(serializer.data)


# Delete Detail Fun
def remove_pri(request,hid):
    if 'private_admin' in request.session:
        user2 = request.session.get('private_admin')
        obj = PrivateModel.objects.get(id = hid)
        if obj.user.username == user2:
            obj.delete()
            return redirect('/view/')
        else:
            return redirect('/view/')
    else:
        return redirect('/')


# Delete Photo Fun
def remove_photo(request,hid):
    if 'private_admin' in request.session:
        user2 = request.session.get('private_admin')
        obj = Private_SubModel.objects.get(id = hid)
        if obj.private_id.user.username == user2:
            jj = obj.private_id.id
            obj.delete()
            return redirect(f'/view/{jj}')
        else:
            return redirect('/view/')
    else:
        return redirect('/')


# Upload Into Google Drive
def download_data(request):
    if request.method == 'POST':
        condition_check = request.POST.get('check')
        if int(condition_check) == 1:
            id = request.POST.get('id')
            try:
                folder_url = upload(id)
                a = {'url': folder_url, 'status': True}
            except Exception as e:
                print('ee1', e)
                a = {'status': False}
        else:
            vall = request.POST.get('folder_id')
            folder_id = vall.split('/')[-1]
            try:
                folder_url = delete_drive(folder_id)
                a = {'url': folder_url, 'status': True}
            except Exception as e:
                print('ee', e)
                a = {'status': False}
        return JsonResponse(a)
    else:
        a = {'status': False}
        return JsonResponse(a)


# Upload Folder, File, Photos/Videos Into Google Drive
def upload(id):
    order = PrivateModel.objects.get(id=id)
    folder_name = str(order.date_name)

    # Login Process Start# Download From console.cloud.google.com
    API_NAME = 'drive'
    API_VERSION = 'v3'
    service = Create_Service(API_NAME, API_VERSION)
    print('service :: ', service)
    # Login Process End

    request_body = {
        'role': 'reader',
        'type': 'anyone',
    }

    # Create a Folder
    folder_type = 'application/vnd.google-apps.folder'
    folder_metadata = {
        'name': folder_name,
        'mimeType': folder_type,
        'parents': ['1sVXo51JUcsULkQBRa2N-BqPEh-_LdzTj']
    }
    folder = service.files().create(
        body=folder_metadata,
        fields='id'
    ).execute()
    folder_id = folder.get('id')

    # Folder Permission
    permission_folder = service.permissions().create(
        fileId=folder_id,
        body=request_body
    ).execute()

    # Print Sharing URL FOLDER
    response_share_link_folder = service.files().get(
        fileId=folder_id,
        fields='webViewLink'
    ).execute()
    folder_url = response_share_link_folder['webViewLink']

    working_dir = os.getcwd()

    file_pathh = working_dir + '/uploads/text.txt'
    with open(file_pathh, "w") as file:
        file.write(str(order.private_description))

templates/private.html
{% extends 'masterpage/index-1.html' %}
{% block title3 %} Private Detail {% endblock %}
{% load static %}
<!--{% load crispy_forms_tags %}-->
{% block content %}


<div class="content-wrapper">
    <section class="content-header">
        <div class="row">
            <div class="col-md-4">
                <h5 class="card-title">Manage Private Window Details</h5>
            </div>
            
            <div class="col-md-2" >
                <div style="text-align-last: center; padding-top:12px; " >
                    <button id="download_button" type="button" onclick="DownloadModel({{order.id}})" class="btn btn-success btn-light" style="
                    color: green; border: green solid 1.7px; padding: 6px 17px;" ><i class="fa fa-download mr-1" style="font-weight: bolder;" ></i> DOWNLOAD</button>
                </div>
            </div>
            <div class="col-md-3">
                <div style="text-align-last: center; padding-top:12px; " >
                    <button type="button" onclick="opensubModel()" class="btn btn-success btn-light" style="
                    color: blue; border: blue solid 1.7px; padding: 6px 17px;" ><i class="fa fa-plus" style="font-weight: bolder;" ></i> ADD PHOTOS/VIDEOS</button>
                </div>
            </div>
            <div class="col-md-3" style=" padding-top:12px; " >
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)"><i class="fa fa-dashboard mr-1"></i> Private</a></li>
                <li class="breadcrumb-item"><a href="/view/">Window</a></li>
                <li class="breadcrumb-item active">Private ID :{{order.id}}</li>
                </ol>
            </div>
        </div>
    </section>


    <!-- Main content -->
    <section class="content" style="min-height: 220px !important;" >
      <div class="row">
		  <div class="col-12">
		    <div class="box">
              <div class="box-body">
				<div class="table-responsive">
					<table class="table text-center" style="color: black !important;" >
						<thead>
							<tr>
                                <th>Date</th>
                                <th>Description</th>
                                <th>Action</th>
							</tr>
						</thead>
						<tbody>
							<tr>
                                <td>{{order.date_name}}</td>
                                <td>{{order.private_description}}</td>
                                <td>
                                    <a href="javascript:void(0)" onclick="updateModel({{order.id}})" class="bg-info mr-2">
                                        <span class="label label-success">
                                            Edit
                                        </span>
                                    </a>
                                    <a href="javascript:void(0)" onclick="Delete({{order.id}})" class="bg-info ml-2">
                                        <span class="label label-danger">
                                            Delete
                                        </span>
                                    </a>
                                    <a href="javascript:void(0)" style="display:none;" id="drive_url" class="bg-info ml-2" target="_blank">
                                        <span class="label label-info">
                                            Drive Url
                                        </span>
                                    </a>
                                    <a href="javascript:void(0)" id='delete_button' style="display:none;" onclick="Delete_drive()" class="bg-info ml-2">
                                        <span class="label label-warning">
                                            Delete Drive
                                        </span>
                                    </a>
    					        </td>
    					    </tr>
						</tbody>
					</table>
				  </div>
              </div>
            </div>
		  </div>
	  </div>
    </section>
	<section class="content" style="min-height: 220px !important; display:none;" id="section_div" >
      <div class="row">
		  <div class="col-12">
		    <div class="box">
              <div class="box-body">
				<div class="table-responsive">
					<table class="table text-center" style="color: black !important;" >
						<thead>
							<tr>
                                <th>Video Id</th>
                                <th>Action</th>
							</tr>
						</thead>
						<tbody>
					    {% for i in lists %}
					        {% if i.type == "video" %}
        					    <tr>
        					        <td>{{i.id}}</td>
        					        <td>
                                        <a href="javascript:void(0)" onclick="Delete_1({{i.id}})" class="bg-info ml-2">
                                            <span class="label label-danger">
                                                Delete
                                            </span>
                                        </a>
        					        </td>
        					    </tr>
        					    {% endif %}
    					    {% endfor %}
					    </tbody>
					</table>
				</div>
              </div>
            </div>
		  </div>
	  </div>
    </section>


    <section class="content">
        <div class="row">
            {% for i in lists %}
		    <div class="col-12 col-lg-6 col-xl-3">
    		    <div class="box">
                    <div class="box-body">
                        <div class="product-img" >
                            <span id="img-{{i.id}}"></span>
                            <div id="check_value{{i.id}}">

                            </div>
        					<div class="pro-img-overlay" id="action{{i.id}}">
        					    <a href="javascript:void(0)" onclick="openphotoModel({{i.id}})" class="bg-info" style="width: auto !important; padding: 10px 25px !important; margin: 0; margin-top: 50px !important;" >View</a>
        					    <a href="javascript:void(0)" onclick="Delete_1({{i.id}})" class="bg-danger" style="width: auto !important; padding: 10px 25px !important; margin: 0; margin-top: 50px !important;" >Delete</a>
    					    </div>
    				    </div>
                    </div>
                </div>
    	    </div>
    	    {% endfor %}
        </div>
    </section>

</div>

<div class="modal center-modal fade" id="categoryModal" tabindex="-1">
  <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
		<h5 class="modal-title " id="add_cat" style="display: none;" >ADD DETAILS</h5>
		<h5 class="modal-title " id="edit_cat" style="display: none;" >EDIT DETAILS</h5>
		<button type="button" class="close" data-dismiss="modal">
		  <span aria-hidden="true">&times;</span>
		</button>
	  </div>
	  <div class="modal-body">
        <form method="POST" id="Addcategory" enctype="multipart/form-data" action="/view/">
          <input type="hidden" name="id" id="id" value="" />
          <div class="form-group">
            <div class="row">
              <div class="col-sm-12">
                {{ m.date_name|as_crispy_field }}
                {{ m.private_description|as_crispy_field }}
              </div>
            </div>
          </div>
          {% csrf_token %}
          <div class="modal-footer">
            <button type="button" class="btn btn-dark" data-dismiss="modal"><span class="text-light">Close</span></button>
            <button type="submit" class="btn btn-primary ">Submit</button>
          </div>
        </form>
      </div>
	</div>
  </div>
</div>

<div class="modal center-modal fade" id="subcategoryModal" tabindex="-1">
  <div class="modal-dialog">
	<div class="modal-content">
	  <div class="modal-header">
		<h5 class="modal-title ">ADD PHOTOS/VIDEOS</h5>
		<button type="button" class="close" data-dismiss="modal">
		  <span aria-hidden="true">&times;</span>
		</button>
	  </div>
	  <div class="modal-body">
        <form method="POST" id="Addcategory" enctype="multipart/form-data">
          <input type="hidden" name="id" id="id" value="" />
          <div class="form-group">
            <div class="row">
              <div class="col-sm-12">
                  <input type="file" multiple name="private_img" id="private_img" >
                  <input type="hidden" id="p_id" name="p_id" value="{{order.id}}" />
              </div>
            </div>
          </div>
          {% csrf_token %}
          <div class="modal-footer">
            <button type="button" class="btn btn-dark" data-dismiss="modal"><span class="text-light">Close</span></button>
            <button type="submit" class="btn btn-primary ">Submit</button>
          </div>
        </form>
      </div>
	</div>
  </div>
</div>

<div class="modal center-modal fade" id="photoModal" tabindex="-1">
  <div class="modal-dialog" style="left: 42%;" id="modal_idd">
	<div class="modal-content" id="modal_openn">
	    <img src="" alt="" style="width: 160%;" id="photo_id">
	</div>
  </div>
</div>


<script>

  function openModel() {
    $('[name="id"]').val("");
    $("#Addcategory")[0].reset();
    $("#add_cat").css('display','block');
    $("#edit_cat").css('display','none');
    // document.getElementById("id_private_img").required = true;
    $('#categoryModal').modal();

  };
  function opensubModel() {
    $('#subcategoryModal').modal();

  };
  function openphotoModel(id) {

      var src_value = $('#photo-'+ id +'').attr('src');
      var photo_ele = document.getElementById("photo_id");
      photo_ele.src = src_value;
      $("#video_id_id").css('display','none');
      $("#photo_id").css('display','block');
      $('#photoModal').modal();

  };

    function DownloadModel(id) {
        let confirmAction = confirm("Download Information");
        if (confirmAction) {
            $('#download_button').prop('disabled', true);
            $('#download_button').css('cursor', 'wait');
            $.ajax({
                url: '/download_data/',
                method: 'POST',
                data: { 'id': id, csrfmiddlewaretoken: '{{csrf_token}}', 'check':1 },
                dataType: 'JSON',

                success: function (data) {
                    if(data.status==true){
                        alert('Drive Uploaded Successfully.....')
                        $('#delete_button').css('cursor', 'pointer');
                        $('#drive_url').attr('href', data.url);
                        $("#drive_url").css('display','inline');
                        $("#delete_button").css('display','inline');
                        $('#download_button').css('cursor', 'not-allowed');
                    }
                    else{

                    }

              },

              error: function () {
                alert('Something is Wrong');
              }
            });
        }
    }
    function Delete_drive() {
        let confirmAction = confirm("Delete Drive");
        if (confirmAction) {
            $('#delete_button').prop('disabled', true);
            $('#delete_button').css('cursor', 'wait');
            var inputValue = document.getElementById('drive_url').getAttribute('href');
            $.ajax({
                url: '/download_data/',
                method: 'POST',
                data: {csrfmiddlewaretoken: '{{csrf_token}}', 'check': 0 , 'folder_id': inputValue},
                dataType: 'JSON',

                success: function (data) {
                    if(data.status==true){
                        alert('Drive Delete Successfully.....')
                        $('#drive_url').attr('href', '');
                        $('#download_button').prop('disabled', false);
                        $('#delete_button').css('display','none');
                        $("#drive_url").css('display','none');
                        $("#download_button").css('display','inline');
                        $('#download_button').css('cursor', 'pointer');
                    }
                    else{

                    }

              },

              error: function () {
                alert('Something is Wrong');
              }
            });
        }
    }
    function updateModel(id) {
        $.ajax({
          url: '/updatepra/',
          method: 'POST',
          data: { 'id': id, csrfmiddlewaretoken: '{{csrf_token}}' },
          dataType: 'JSON',

          success: function (data) {
            $('[name="id"]').val(data.id);
            $('#id_date_name').val(data.date_name);
            $('#id_private_description').val(data.private_description);
            // document.getElementById("id_private_img").required = false;
            $("#add_cat").css('display','none');
            $("#edit_cat").css('display','block');
            $('#categoryModal').modal();
          },

          error: function () {
            alert('Something is Wrong');
          }
        });
    }

    function Delete(id){
        let confirmAction = confirm("You want to delete Private Item?")
        if (confirmAction){
            window.location.href = "/remove_pri/" + id + "";
        }
        else{

        }
    }
    function Delete_1(id){
        let confirmAction = confirm("You want to delete Photo?")
        if (confirmAction){
            window.location.href = "/remove_photo/" + id + "";
        }
        else{

        }
    }

</script>
{% endblock %}